name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    runs:
      using: "composite"
      steps:
        - uses: actions/checkout@v2
        - name: Install udev
          run: sudo apt-get install -y libudev-dev
        - name: Build for ubuntu
          run: cargo build --verbose

